# frozen_string_literal: true

source 'https://rubygems.org'

gem 'bcrypt'
gem 'device_detector'
gem 'dry-transaction'
gem 'dry-validation'
gem 'geocoder'
gem 'mongoid'
gem 'puma'
gem 'sinatra'

group :development do
  gem 'debug'
  gem 'rubocop'
  gem 'ruby-prof'
end
